apiVersion: v1
data:
  000-core.yaml: |
    admin:
      endpoint: localhost:8089
      insecure: true
    catalog-cache:
      endpoint: localhost:8081
      insecure: true
      type: datacatalog
    cluster_resources:
      standaloneDeployment: false
      templatePath: /etc/flyte/cluster-resource-templates
    logger:
      show-source: true
      level: 1
    propeller:
      create-flyteworkflow-crd: true
    webhook:
      certDir: /var/run/flyte/certs
      localCert: true
      secretName: flyte-binary-webhook-secret
      serviceName: flyte-binary-webhook
      servicePort: 443
    flyte:
      admin:
        disableClusterResourceManager: false
        disableScheduler: false
        disabled: false
        seedProjects:
        - flytesnacks
      dataCatalog:
        disabled: false
      propeller:
        disableWebhook: false
        disabled: false
  001-plugins.yaml: |
    tasks:
      task-plugins:
        default-for-task-types:
          container: container
          container_array: k8s-array
          sidecar: sidecar
        enabled-plugins:
        - container
        - sidecar
        - k8s-array
        - agent-service
    plugins:
      logs:
        kubernetes-enabled: false
        cloudwatch-enabled: false
        stackdriver-enabled: false
      k8s:
        co-pilot:
          image: "cr.flyte.org/flyteorg/flytecopilot-release:v1.10.6"
      k8s-array:
        logs:
          config:
            kubernetes-enabled: false
            cloudwatch-enabled: false
            stackdriver-enabled: false
      agent-service:
        defaultAgent:
          defaultTimeout: 10s
          endpoint: dns:///flyteagent.flyte.svc.cluster.local:8000
          insecure: true
          timeouts:
            GetTask: 10s
        supportedTaskTypes:
        - default_task
  002-database.yaml: |
    database:
      postgres:
        username: postgres
        host: education-eks-vv8vcaqw-flyte-db.cdhzgmmntzio.us-east-1.rds.amazonaws.com
        port: 5432
        dbname: flyteadmin
        options: "sslmode=require"
  003-storage.yaml: |
    propeller:
      rawoutput-prefix: s3://education-eks-vv8vcaqw-flyte-userdata-vv8vcaqw/data
    storage:
      type: stow
      stow:
        kind: s3
        config:
          region: us-east-1
          disable_ssl: false
          v2_signing: false
          auth_type: iam
      container: education-eks-vv8vcaqw-flyte-metadata-vv8vcaqw
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: flyte-binary
    meta.helm.sh/release-namespace: flyte
  creationTimestamp: "2025-07-26T03:53:41Z"
  labels:
    app.kubernetes.io/instance: flyte-binary
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: flyte-binary
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: flyte-binary-v1.10.6
  name: flyte-binary-config
  namespace: flyte
  resourceVersion: "631332"
  uid: fa027429-1771-49c8-8593-36f90853c368
